### ISSUE TITLE
post review by idea 14 return 400 error.

### ISSUE THREAD

**Issue by isoloist** [kaneg/reviewboard-plugin-for-idea#5]
I have downloaded the source code and try to debug the plugin. when post diff by http://reviewboard.xxx.com/api/review-requests/xxxxxx/diffs/   return http 400 code. 
post data is :

-----------------------------1ah0ywxu50ibr1nr4dmvr9qtovmsmioh2hs4tt
Content-Disposition: form-data; name="path"; filename="review.diff"

Index: application.properties
===================================================================
--- application.properties	(revision 2645)
+++ application.properties	(revision )
@@ -2,4 +2,4 @@
 #Thu Apr 30 18:08:41 CST 2015
 app.grails.version=2.5.0
 app.name=bizflow
-app.version=1.0
+app.version=1.2

-----------------------------1ah0ywxu50ibr1nr4dmvr9qtovmsmioh2hs4tt
Content-Disposition: form-data; name="basedir"

/XXX/trunk
-----------------------------1ah0ywxu50ibr1nr4dmvr9qtovmsmioh2hs4tt--

I want to fix this bug in idea 14. can anyone give me some help

**Comment by kaneg** [comment]
Hello,

What's your version control system? Git or svn?

Do you configure the repository in your review board system?

Do you choose correct repository in the repository list?

-Kane

**Comment by isoloist** [comment]
I use svn  1.7 and ReviewBoard 1.6.1 . I'am sure chose the correct svn repo.

**Comment by pranavpc** [comment]
guys i am following this.. if fixed please integrate changes into trunk

On Mon, Aug 24, 2015 at 9:33 PM, kexiaocheng <notifications@github.com>
wrote:

> I use svn 1.7 and ReviewBoard 1.6.1 . I'am sure chose the correct svn repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaneg/reviewboard-plugin-for-idea/issues/5#issuecomment-134201767>
> .
>



-- 
Best,
Pranav.

**Comment by kaneg** [comment]
guys,
I really want to help on the issue. However I haven't encountered such case in my environment. Since the issue is environment specific, I suggest you download the source and debug it in IDEA to check what happened during your post review.

-Kane

**Comment by isoloist** [comment]
i solved the problem by reinstall  the svn client to 1.714 on my computer(OS X 10.10). Because my svn server version is 1.6 . Thanks for @kaneg and @pranavpc .
