### ISSUE TITLE
diff file gets wrong encoding

### ISSUE THREAD

**Issue by yqt** [kaneg/reviewboard-plugin-for-idea#6]
Hi,

The default encoding of my system is GBK while encoding of project is UTF-8. Non-ascii characters in diff file attached to the review issue are gibberish.

I saw a previous commit has mentioned the encoding issue. But it seems that the problem persists.

Maybe the following line should add "UTF-8"?
https://github.com/kaneg/reviewboard-plugin-for-idea/blob/0e259d49d69e4fcb6ef84585e19a2afb278c4e8f/src/rb/MemoryFile.java#L38

Thanks.

**Comment by kaneg** [comment]
Thank you for pointing the encoding issue. It has been resolved in the latest release 2.1. You can download and take a look.
